# Generated by Django 5.0.1 on 2024-01-27 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0002_userdetails_userqualifications_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userqualifications',
            name='address',
            field=models.TextField(default='No Address'),
        ),
        migrations.AlterField(
            model_name='userqualifications',
            name='education',
            field=models.CharField(blank=True, default='No Education', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userqualifications',
            name='hobbies',
            field=models.TextField(blank=True, default='No Hobbies', null=True),
        ),
        migrations.AlterField(
            model_name='userqualifications',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
