# Generated by Django 5.0.1 on 2024-01-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0003_alter_userdetails_age_alter_userdetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqualifications',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userqualifications',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userqualifications',
            name='hobbies',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
