# Generated by Django 5.0.1 on 2024-01-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0005_alter_userdetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userqualifications',
            name='education',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
