# Generated by Django 5.0.1 on 2024-01-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
